// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUpuYNjYUUwJ3l0xVyX2C2ydkWc5tCbQE',
    appId: '1:422295829493:web:26975b0eb1e4723ff4bebc',
    messagingSenderId: '422295829493',
    projectId: 'flutter-auth-app-c9f7e',
    authDomain: 'flutter-auth-app-c9f7e.firebaseapp.com',
    storageBucket: 'flutter-auth-app-c9f7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMwo7rCV1-6YeLZq6sdejL2s0TVl4OWlY',
    appId: '1:422295829493:android:19c17a07e97c52e1f4bebc',
    messagingSenderId: '422295829493',
    projectId: 'flutter-auth-app-c9f7e',
    storageBucket: 'flutter-auth-app-c9f7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Lh7kRRt6k5UGta3lHz6ErbKt-M_5blM',
    appId: '1:422295829493:ios:b4095fb6cd8035d5f4bebc',
    messagingSenderId: '422295829493',
    projectId: 'flutter-auth-app-c9f7e',
    storageBucket: 'flutter-auth-app-c9f7e.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );
}
